# Generated by Django 5.2.1 on 2025-07-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_remove_flight_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked_In')], default='booked', max_length=20)),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flight', to='Flights.flight')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
