# Generated by Django 5.2.1 on 2025-07-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0003_guestbooking_delete_booking_delete_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbooking',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='guestbooking',
            old_name='last',
            new_name='last_name',
        ),
    ]
