# Generated by Django 5.2.1 on 2025-07-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
    ]
