# Generated by Django 5.2.1 on 2025-07-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0004_rename_first_guestbooking_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbooking',
            name='flights',
        ),
    ]
