# Generated by Django 5.2.1 on 2025-07-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0005_remove_guestbooking_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbooking',
            name='flight',
            field=models.ForeignKey(default=317, on_delete=django.db.models.deletion.CASCADE, related_name='booking_flight', to='Flights.flight'),
            preserve_default=False,
        ),
    ]
